@startuml BasicOOP Class
skinparam ClassAttributeIconSize 0
class Cat {
  + name
  + age
  + sex
  + weight
  + color
  ...
  + breath()
  + eat(food)
  + run(destination)
  + sleep(hours)
  + meow()
}

object "Oscar: Cat" as catOscar {
  name = "Oscar"
  sex = "male"
  age = 3
  weight = 7
  color = brow
  texture = strippd
}

object "Luna: Cat" as catLuna {
  name = "Luna"
  sex = "female"
  age = 2
  weight = 5
  color = gray
  texture = plain
}
@enduml