@startuml BasicOOP Class
skinparam ClassAttributeIconSize 0
class Cat {
  + name
  + age
  + gender
  + weight
  + color
  ...
  + breath()
  + eat(food)
  + run(destination)
  + sleep(hours)
  + meow()
}
@enduml